//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBall.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public string Reyler { get; set; }
        public string tapsiriq { get; set; }
        public Nullable<int> musteri_id { get; set; }
    
        public virtual Musteri Musteri { get; set; }
    }
}
