//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBall.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FootBallEntities : DbContext
    {
        public FootBallEntities()
            : base("name=FootBallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<Musteri> Musteris { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Rezerv> Rezervs { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<Stadium> Stadia { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
