//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBall.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int id { get; set; }
        public Nullable<System.DateTime> reports_date { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> reserv_id { get; set; }
    
        public virtual Rezerv Rezerv { get; set; }
    }
}
