//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBall.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezerv()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public int id { get; set; }
        public Nullable<int> musteri_id { get; set; }
        public Nullable<System.DateTime> reserv_date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> rooms_id { get; set; }
        public Nullable<int> stadium_id { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        public virtual room room { get; set; }
        public virtual Stadium Stadium { get; set; }
    }
}
